### ISSUE TITLE
Cannot create environments: No such file or directory […]etc/apt/sources.list 

### ISSUE THREAD

**Issue by bascht** [Max00355/Coffer#1]
Thanks for creating Coffer, it looks really interesting so far. :smiley:. At the moment (latest master) I cannot create environments – it looks like it fails to create the necessary directory structure:

``` bash
$ rm -rf /root/.coffer
$ coffer create testenv
Creating environment directory
Copying necessary files over. This could take a bit.
E: Couldn't work out current architecture
Traceback (most recent call last):
  File "/usr/bin/coffer", line 9, in <module>
    load_entry_point('Coffer==1.0.0', 'console_scripts', 'coffer')()
  File "build/bdist.linux-x86_64/egg/coffer/coffer.py", line 31, in checkArgs
  File "build/bdist.linux-x86_64/egg/coffer/create.py", line 51, in create
  File "build/bdist.linux-x86_64/egg/coffer/create.py", line 23, in copyBaseFiles
IOError: [Errno 2] No such file or directory: '/root/.coffer/envs/testenv/etc/apt/sources.list'

$ find /root/.coffer
.coffer/
.coffer/debootstrap
.coffer/debootstrap/Makefile
.coffer/debootstrap/scripts
.coffer/debootstrap/scripts/woody.buildd
.coffer/debootstrap/scripts/wheezy
.coffer/debootstrap/scripts/karmic
.coffer/debootstrap/scripts/woody
.coffer/debootstrap/scripts/oldstable
.coffer/debootstrap/scripts/breezy
.coffer/debootstrap/scripts/jaunty
.coffer/debootstrap/scripts/aequorea
.coffer/debootstrap/scripts/maverick
.coffer/debootstrap/scripts/sarge
.coffer/debootstrap/scripts/lucid
.coffer/debootstrap/scripts/potato
.coffer/debootstrap/scripts/stretch
.coffer/debootstrap/scripts/feisty
.coffer/debootstrap/scripts/gutsy
.coffer/debootstrap/scripts/sid
.coffer/debootstrap/scripts/unstable
.coffer/debootstrap/scripts/sarge.fakechroot
.coffer/debootstrap/scripts/oneiric
.coffer/debootstrap/scripts/vivid
.coffer/debootstrap/scripts/raring
.coffer/debootstrap/scripts/jessie-kfreebsd
.coffer/debootstrap/scripts/warty
.coffer/debootstrap/scripts/utopic
.coffer/debootstrap/scripts/warty.buildd
.coffer/debootstrap/scripts/bartholomea
.coffer/debootstrap/scripts/sarge.buildd
.coffer/debootstrap/scripts/yakkety
.coffer/debootstrap/scripts/etch-m68k
.coffer/debootstrap/scripts/jessie
.coffer/debootstrap/scripts/dasyatis
.coffer/debootstrap/scripts/lenny
.coffer/debootstrap/scripts/saucy
.coffer/debootstrap/scripts/dapper
.coffer/debootstrap/scripts/etch
.coffer/debootstrap/scripts/wily
.coffer/debootstrap/scripts/hoary
.coffer/debootstrap/scripts/xenial
.coffer/debootstrap/scripts/testing
.coffer/debootstrap/scripts/intrepid
.coffer/debootstrap/scripts/edgy
.coffer/debootstrap/scripts/chromodoris
.coffer/debootstrap/scripts/trusty
.coffer/debootstrap/scripts/squeeze
.coffer/debootstrap/scripts/hardy
.coffer/debootstrap/scripts/quantal
.coffer/debootstrap/scripts/hoary.buildd
.coffer/debootstrap/scripts/precise
.coffer/debootstrap/scripts/stable
.coffer/debootstrap/scripts/natty
.coffer/debootstrap/debootstrap.8
.coffer/debootstrap/README
.coffer/debootstrap/TODO
.coffer/debootstrap/debootstrap
.coffer/debootstrap/debian
.coffer/debootstrap/debian/changelog
.coffer/debootstrap/debian/copyright
.coffer/debootstrap/debian/debootstrap.manpages
.coffer/debootstrap/debian/debootstrap.docs
.coffer/debootstrap/debian/control
.coffer/debootstrap/debian/source
.coffer/debootstrap/debian/source/format
.coffer/debootstrap/debian/source/options
.coffer/debootstrap/debian/rules
.coffer/debootstrap/debian/compat
.coffer/debootstrap/functions
.coffer/envs
.coffer/envs/testenv
```

Am I holding it wrong? :smile:

**Comment by f-prime** [comment]
Ahhh, I see the issue here I think. Coffer uses Debootstrap to create the environments and it seems debootstrap can't make out your architecture, it needs to be specified. Unfortunately I'm not getting this error which makes it more difficult to debug. Could you tell me what system you're running?

**Comment by f-prime** [comment]
Also, are you by any chance on Fedora, or using CentOS? After some googling it seems this will happen on a system without dpkg installed.

**Comment by f-prime** [comment]
@bascht I have pushed a commit in the branch `1.1.0` that might fix this problem. Would you mind checking out to that branch and trying it out? Thanks! You'll have to delete your `~/.coffer` folder when you do this.

**Comment by bascht** [comment]
Thanks for looking into it! :)  Yes, I'm on Fedora 24, and my first try was using Python 2.7 (which is the standard `python` from $PATH.  I tried both 2.7.11 and 3.5.1 now:

### 2.7.11

```
$ coffer create myenv
Traceback (most recent call last):
  File "/usr/bin/coffer", line 9, in <module>
    load_entry_point('Coffer==1.1.0', 'console_scripts', 'coffer')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/coffer/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/coffer/coffer.py", line 2, in <module>
ImportError: cannot import name create
```

### 3.5.1

```
$  coffer create myenv
Setting up environment
Downloading necessary files
Traceback (most recent call last):
  File "/usr/bin/coffer", line 9, in <module>
    load_entry_point('Coffer==1.1.0', 'console_scripts', 'coffer')()
  File "/usr/lib/python3.5/site-packages/Coffer-1.1.0-py3.5.egg/coffer/coffer.py", line 15, in checkArgs
  File "/usr/lib/python3.5/site-packages/Coffer-1.1.0-py3.5.egg/coffer/utils/setupEnv.py", line 12, in setup
AttributeError: module 'urllib' has no attribute 'urlopen'
```

Both times without a `~/.coffer` folder.  :)

**Comment by f-prime** [comment]
Okay, cool, so coffer has been ported to Python 3 in `1.1.0` so 3.5.1 should work. I guess I just didn't port everything correctly, haha. Fixing now.

**Comment by f-prime** [comment]
@bascht Just pushed the change that should fix the urllib error. If something is still broken then I will take a more in depth look at it later today. Thanks for your help!

**Comment by bascht** [comment]
@Max00355 So e74be88 fixes the Python 3 import error, but not the original problem:

```
coffer create myenv
Setting up environment
Downloading necessary files
Creating environment directory
Copying necessary files over. This could take a bit.
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
I: Retrieving Release 
E: Failed getting release file https://mirrors.kernel.org/debian/dists/precise/Release
Traceback (most recent call last):
  File "/usr/bin/coffer", line 9, in <module>
    load_entry_point('Coffer==1.1.0', 'console_scripts', 'coffer')()
  File "/usr/lib/python3.5/site-packages/Coffer-1.1.0-py3.5.egg/coffer/coffer.py", line 31, in checkArgs
  File "/usr/lib/python3.5/site-packages/Coffer-1.1.0-py3.5.egg/coffer/create.py", line 51, in create
  File "/usr/lib/python3.5/site-packages/Coffer-1.1.0-py3.5.egg/coffer/create.py", line 23, in copyBaseFiles
FileNotFoundError: [Errno 2] No such file or directory: '/root/.coffer/envs/myenv/etc/apt/sources.list'
```

Debootstrap itself works for me:

```
$ debootstrap --arch=amd64 jessie jessie
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
I: Retrieving Release 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: acl adduser dmsetup insserv libaudit-common libaudit1 libbz2-1.0 libcap2 libcap2-bin libcryptsetup4 libdb5.3 libdebconfclient0 libdevmapper1.02.1 libgcrypt20 libgpg-error0 libkmod2 libncursesw5 libprocps3 libsemanage-common libsemanage1 libslang2 libsystemd0 libudev1 libustr-1.0-1 procps systemd systemd-sysv udev 
I: Found additional base dependencies: libcurl3-gnutls libdns-export100 libffi6 libgmp10 libgnutls-deb0-28 libgnutls-openssl27 libgssapi-krb5-2 libhogweed2 libicu52 libidn11 libirs-export91 libisc-export95 libisccfg-export90 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libmnl0 libnetfilter-acct1 libnettle4 libnfnetlink0 libp11-kit0 libpsl0 librtmp1 libsasl2-2 libsasl2-modules-db libssh2-1 libtasn1-6 openssl 
I: Checking component main on https://mirrors.kernel.org/debian...
I: Retrieving acl 2.2.52-2
I: Validating acl 2.2.52-2
I: Retrieving libacl1 2.2.52-2
I: Validating libacl1 2.2.52-2
I: Retrieving adduser 3.113+nmu3
```

**Comment by f-prime** [comment]
Okay, I see, I'll have to install Fedora and debug this myself. I'll get back to you. Hopefully I'll have this fixed tonight. Unless you'd like to take a look at it, but never the less I'll get this fixed. Thanks again.

**Comment by bascht** [comment]
No hurries. Maybe I find the time to fiddle around with it myself. ;)

**Comment by f-prime** [comment]
@bascht So I believe that it has to do with the version of ubuntu that is being installed in the environment. You said that `jessie` worked, so I added a flag to `-v` to create that allows you to specify the version of debian/ubuntu that is installed in the environment. 

Could you try doing `sudo coffer create test -v jessie` and tell me if that works?  

I haven't updated the docs yet for create to give all the information of `-v`

**Comment by bascht** [comment]
@Max00355 Yap! That did the trick.

```
[root@kandalingo ~]# coffer create test -v jessie
Setting up environment
Downloading necessary files
Creating environment directory
Copying necessary files over. This could take a bit.
Using version jessie
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
I: Retrieving Release 
I: Retrieving Packages 
I: Validating Packages 
[…]
```

Thanks for the version flag! 

For future (e.g. Ubuntu)-Support, debootstrap also can be supplied with a full mirror URL, so that might be something to look into! :)

```
debootstrap --arch=amd64 xenial xenial http://archive.ubuntu.com/ubuntu/
```

Thanks for the fix! :+1:

**Comment by f-prime** [comment]
@bascht Great! Glad to hear it's working for you. I managed to get it to work in a VM on my side, but I was still having issue with `apt-get` but that may be another issue. 

I will be adding more flags to control the rest of the debootstrap functionalities probably in 1.2.x but this is enough for me to justify merging 1.1.0 into master, so thanks for your help on this!
